package remote.com.example.huangli.punchcard.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import remote.com.example.huangli.punchcard.dao.TaskEntity;
import remote.com.example.huangli.punchcard.dao.CardEntity;
import remote.com.example.huangli.punchcard.dao.PlanEntity;
import remote.com.example.huangli.punchcard.dao.UserEntity;

import remote.com.example.huangli.punchcard.dao.TaskEntityDao;
import remote.com.example.huangli.punchcard.dao.CardEntityDao;
import remote.com.example.huangli.punchcard.dao.PlanEntityDao;
import remote.com.example.huangli.punchcard.dao.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskEntityDaoConfig;
    private final DaoConfig cardEntityDaoConfig;
    private final DaoConfig planEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final TaskEntityDao taskEntityDao;
    private final CardEntityDao cardEntityDao;
    private final PlanEntityDao planEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        cardEntityDaoConfig = daoConfigMap.get(CardEntityDao.class).clone();
        cardEntityDaoConfig.initIdentityScope(type);

        planEntityDaoConfig = daoConfigMap.get(PlanEntityDao.class).clone();
        planEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);
        cardEntityDao = new CardEntityDao(cardEntityDaoConfig, this);
        planEntityDao = new PlanEntityDao(planEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(TaskEntity.class, taskEntityDao);
        registerDao(CardEntity.class, cardEntityDao);
        registerDao(PlanEntity.class, planEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        taskEntityDaoConfig.getIdentityScope().clear();
        cardEntityDaoConfig.getIdentityScope().clear();
        planEntityDaoConfig.getIdentityScope().clear();
        userEntityDaoConfig.getIdentityScope().clear();
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

    public CardEntityDao getCardEntityDao() {
        return cardEntityDao;
    }

    public PlanEntityDao getPlanEntityDao() {
        return planEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
