package remote.com.example.huangli.punchcard.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import remote.com.example.huangli.punchcard.dao.TaskEntity;
import remote.com.example.huangli.punchcard.dao.CardEntity;

import remote.com.example.huangli.punchcard.dao.TaskEntityDao;
import remote.com.example.huangli.punchcard.dao.CardEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskEntityDaoConfig;
    private final DaoConfig cardEntityDaoConfig;

    private final TaskEntityDao taskEntityDao;
    private final CardEntityDao cardEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        cardEntityDaoConfig = daoConfigMap.get(CardEntityDao.class).clone();
        cardEntityDaoConfig.initIdentityScope(type);

        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);
        cardEntityDao = new CardEntityDao(cardEntityDaoConfig, this);

        registerDao(TaskEntity.class, taskEntityDao);
        registerDao(CardEntity.class, cardEntityDao);
    }
    
    public void clear() {
        taskEntityDaoConfig.getIdentityScope().clear();
        cardEntityDaoConfig.getIdentityScope().clear();
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

    public CardEntityDao getCardEntityDao() {
        return cardEntityDao;
    }

}
