package remote.com.example.huangli.punchcard.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import remote.com.example.huangli.punchcard.dao.PlanEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLAN_ENTITY.
*/
public class PlanEntityDao extends AbstractDao<PlanEntity, String> {

    public static final String TABLENAME = "PLAN_ENTITY";

    /**
     * Properties of entity PlanEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Account = new Property(0, String.class, "account", true, "ACCOUNT");
        public final static Property Num = new Property(1, String.class, "num", false, "NUM");
        public final static Property Describe = new Property(2, String.class, "describe", false, "DESCRIBE");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
    };


    public PlanEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PlanEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLAN_ENTITY' (" + //
                "'ACCOUNT' TEXT PRIMARY KEY NOT NULL ," + // 0: account
                "'NUM' TEXT NOT NULL ," + // 1: num
                "'DESCRIBE' TEXT NOT NULL ," + // 2: describe
                "'TYPE' INTEGER NOT NULL );"); // 3: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLAN_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlanEntity entity) {
        stmt.clearBindings();
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(1, account);
        }
        stmt.bindString(2, entity.getNum());
        stmt.bindString(3, entity.getDescribe());
        stmt.bindLong(4, entity.getType());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlanEntity readEntity(Cursor cursor, int offset) {
        PlanEntity entity = new PlanEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // account
            cursor.getString(offset + 1), // num
            cursor.getString(offset + 2), // describe
            cursor.getInt(offset + 3) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlanEntity entity, int offset) {
        entity.setAccount(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNum(cursor.getString(offset + 1));
        entity.setDescribe(cursor.getString(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(PlanEntity entity, long rowId) {
        return entity.getAccount();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(PlanEntity entity) {
        if(entity != null) {
            return entity.getAccount();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
