package remote.com.example.huangli.punchcard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAN_ENTITY.
 */
public class PlanEntity {

    private String account;
    /** Not-null value. */
    private String num;
    /** Not-null value. */
    private String describe;
    private int type;

    public PlanEntity() {
    }

    public PlanEntity(String account) {
        this.account = account;
    }

    public PlanEntity(String account, String num, String describe, int type) {
        this.account = account;
        this.num = num;
        this.describe = describe;
        this.type = type;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getNum() {
        return num;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNum(String num) {
        this.num = num;
    }

    /** Not-null value. */
    public String getDescribe() {
        return describe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

}
