package remote.com.example.huangli.punchcard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK_ENTITY.
 */
public class TaskEntity {

    private String num;
    /** Not-null value. */
    private String describe;
    private boolean isComplated;
    /** Not-null value. */
    private String remindDays;

    public TaskEntity() {
    }

    public TaskEntity(String num) {
        this.num = num;
    }

    public TaskEntity(String num, String describe, boolean isComplated, String remindDays) {
        this.num = num;
        this.describe = describe;
        this.isComplated = isComplated;
        this.remindDays = remindDays;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    /** Not-null value. */
    public String getDescribe() {
        return describe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public boolean getIsComplated() {
        return isComplated;
    }

    public void setIsComplated(boolean isComplated) {
        this.isComplated = isComplated;
    }

    /** Not-null value. */
    public String getRemindDays() {
        return remindDays;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRemindDays(String remindDays) {
        this.remindDays = remindDays;
    }

}
