package remote.com.example.huangli.punchcard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK_ENTITY.
 */
public class TaskEntity {

    /** Not-null value. */
    private String key;
    /** Not-null value. */
    private String describe;
    private boolean isComplated;
    /** Not-null value. */
    private String remindDays;

    public TaskEntity() {
    }

    public TaskEntity(String key, String describe, boolean isComplated, String remindDays) {
        this.key = key;
        this.describe = describe;
        this.isComplated = isComplated;
        this.remindDays = remindDays;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getDescribe() {
        return describe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public boolean getIsComplated() {
        return isComplated;
    }

    public void setIsComplated(boolean isComplated) {
        this.isComplated = isComplated;
    }

    /** Not-null value. */
    public String getRemindDays() {
        return remindDays;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRemindDays(String remindDays) {
        this.remindDays = remindDays;
    }

}
