package remote.com.example.huangli.punchcard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_ENTITY.
 */
public class UserEntity {

    private String account;
    /** Not-null value. */
    private String passoword;
    /** Not-null value. */
    private String nickname;
    /** Not-null value. */
    private String signature;
    private int lv;
    private int curProgress;

    public UserEntity() {
    }

    public UserEntity(String account) {
        this.account = account;
    }

    public UserEntity(String account, String passoword, String nickname, String signature, int lv, int curProgress) {
        this.account = account;
        this.passoword = passoword;
        this.nickname = nickname;
        this.signature = signature;
        this.lv = lv;
        this.curProgress = curProgress;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getPassoword() {
        return passoword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassoword(String passoword) {
        this.passoword = passoword;
    }

    /** Not-null value. */
    public String getNickname() {
        return nickname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /** Not-null value. */
    public String getSignature() {
        return signature;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    public int getLv() {
        return lv;
    }

    public void setLv(int lv) {
        this.lv = lv;
    }

    public int getCurProgress() {
        return curProgress;
    }

    public void setCurProgress(int curProgress) {
        this.curProgress = curProgress;
    }

}
